name: Show Name

on:
  push:
    branches:
      - main

jobs:
  show-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bash Script
      run: |
        chmod +x show_name.sh
        ./show_name.sh
